# Config file for training SDF model

seed: 36   # Seed for reproducibility

# training
epochs: 2000
lr_model: 0.0001   # Initial learning rate (model)
lr_latent: 0.0001  # Initial learning rate (latent vector)
batch_size: 16384
sigma_regulariser: 0.001  # Sigma value as regulariser in the loss function
loss_multiplier: 1   # Loss multiplier
clamp: False # Clip the network prediction
clamp_value: 0.5 # Value for clipping

# architecture
num_layers: 8   # Num network layers
inner_dim: 1024 # Inner dimensions of the network
latent_size: 512  # Size of the latent vector
skip_connections: True

# lr_scheduling
lr_scheduler: True   # Learning rate scheduling
lr_multiplier: 0.9   # Multiplier for the learning rate scheduling
patience: 20   # Patience inthe learning rate scheduling

# pretrained
pretrained: False   # Use pretrain weights
pretrain_weights: ''   # Path to pretrain weights
pretrain_optim_model: ''   # Path to pretrain weights (model)
pretrain_optim_latent: ''   # Path to pretrain weights (latent codes)

# Config file for training GCN model

GCN_tag_dim: 4 # Must be the same as number of ifc_classes
GCN_feature_channels: 512
GCN_hidden_channels: 1024

GCN_epochs: 1000
GCN_lr_model: 0.00001
GCN_batch_size: 1